spring.application.name=demo

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/tnp?currentSchema=practice
spring.r2dbc.username=tnp
spring.r2dbc.password=password
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.graphql.graphiql.enabled=true

spring.grpc.server.reflection.enabled=true
spring.grpc.server.port=9090

spring.rsocket.server.port=7000
